# Generated by Django 3.2.4 on 2021-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_show_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
